-- CSE Permission & Leave Tracking System Database Schema
-- Target: Supabase Postgres (PostgreSQL 15+)
--
-- Run in the Supabase SQL editor, or:
--   psql "$DATABASE_URL" -f migrations/schema.sql
--
-- This script is NOT incremental. Re-running it drops and recreates the tables,
-- which deletes every user, request, proof record and attendance mark. Load it
-- once against an empty project.

BEGIN;

DROP TABLE IF EXISTS attendance_records, class_members, class_groups,
                     approval_history, proof_documents, permission_requests,
                     users CASCADE;
DROP TYPE IF EXISTS user_role, permission_type, request_status,
                     approval_action, attendance_status CASCADE;

-- Enum types. MySQL's inline ENUM becomes a named Postgres type here, which
-- keeps the same set of legal values and makes bad inserts fail loudly.
CREATE TYPE user_role AS ENUM ('STUDENT', 'LECTURER', 'HOD');
CREATE TYPE permission_type AS ENUM ('LEAVE', 'CLASSROOM');
CREATE TYPE request_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED');
CREATE TYPE approval_action AS ENUM ('APPROVED', 'REJECTED');
CREATE TYPE attendance_status AS ENUM ('PRESENT', 'ABSENT', 'ON_PERMISSION');

-- updated_at trigger.
-- MySQL's "ON UPDATE CURRENT_TIMESTAMP" has no Postgres equivalent, so every
-- table that relied on it gets a trigger instead.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Users table
-- Student mailboxes are provisioned as <rollno>@adityauniversity.in in lower
-- case (for example 26b21cs058@adityauniversity.in) and the Outlook display
-- name is the same roll number, so roll_number is the authoritative student
-- identifier. `name` mirrors it for students; staff keep their real name.
CREATE TABLE users (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    microsoft_id  varchar(255) UNIQUE,
    email         varchar(255) NOT NULL UNIQUE,
    name          varchar(255) NOT NULL,
    roll_number   varchar(50) UNIQUE,
    phone         varchar(20),
    role          user_role NOT NULL DEFAULT 'STUDENT',
    department    varchar(100) DEFAULT 'CSE',
    is_active     boolean NOT NULL DEFAULT TRUE,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_email ON users (email);
CREATE INDEX idx_roll_number ON users (roll_number);
CREATE INDEX idx_role ON users (role);

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- Permission requests table
CREATE TABLE permission_requests (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id            integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_type       permission_type NOT NULL,
    reason                text NOT NULL,
    start_date            date NOT NULL,
    end_date              date NOT NULL,
    start_time            time,
    end_time              time,
    status                request_status NOT NULL DEFAULT 'PENDING',
    assigned_faculty_id   integer REFERENCES users(id) ON DELETE SET NULL,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_student_id ON permission_requests (student_id);
CREATE INDEX idx_status ON permission_requests (status);
CREATE INDEX idx_permission_type ON permission_requests (permission_type);
CREATE INDEX idx_dates ON permission_requests (start_date, end_date);

CREATE TRIGGER trg_requests_updated_at BEFORE UPDATE ON permission_requests
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- Proof documents table.
-- file_path is an object key in the private Supabase Storage bucket, not a
-- filesystem path. The original filename never becomes a path component.
CREATE TABLE proof_documents (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          integer NOT NULL REFERENCES permission_requests(id) ON DELETE CASCADE,
    original_filename   varchar(255) NOT NULL,
    stored_filename     varchar(255) NOT NULL,
    file_path           varchar(500) NOT NULL,
    file_type           varchar(50) NOT NULL,
    file_size           integer NOT NULL,
    uploaded_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_request_id ON proof_documents (request_id);

-- Approval history table
CREATE TABLE approval_history (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id  integer NOT NULL REFERENCES permission_requests(id) ON DELETE CASCADE,
    faculty_id  integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action      approval_action NOT NULL,
    remarks     text,
    actioned_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_request_id_history ON approval_history (request_id);
CREATE INDEX idx_faculty_id ON approval_history (faculty_id);

-- Class groups -------------------------------------------------------------
-- A lecturer creates a class, then bulk-loads the roster from a spreadsheet of
-- roll numbers. Members can be stored before the student account exists
-- (student_id NULL), so an uploaded roster links up automatically once that
-- student signs in for the first time.

CREATE TABLE class_groups (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(120) NOT NULL,
    section_code   varchar(40),
    academic_year  varchar(20),
    faculty_id     integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_faculty ON class_groups (faculty_id);

CREATE TABLE class_members (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id     integer NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE,
    student_id   integer REFERENCES users(id) ON DELETE SET NULL,
    roll_number  varchar(50) NOT NULL,
    enrolled     boolean NOT NULL DEFAULT TRUE,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_class_roll UNIQUE (class_id, roll_number)
);

CREATE INDEX idx_class ON class_members (class_id);
CREATE INDEX idx_student ON class_members (student_id);
CREATE INDEX idx_roll_lookup ON class_members (roll_number);

-- Attendance ---------------------------------------------------------------
-- One row per student per class per day. ON_PERMISSION marks a student excused
-- because an approved permission covers that date.
-- The named unique constraint is what AttendanceModel.save() conflicts on.

CREATE TABLE attendance_records (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id         integer NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE,
    student_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    attendance_date  date NOT NULL,
    status           attendance_status NOT NULL,
    marked_by        integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    marked_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_attendance UNIQUE (class_id, student_id, attendance_date)
);

CREATE INDEX idx_class_date ON attendance_records (class_id, attendance_date);

-- Row Level Security -------------------------------------------------------
-- Every table lives in the exposed `public` schema. This application connects
-- over psycopg with the project owner role and does all authorisation in
-- Python, so no `anon` or `authenticated` policy is granted here: enabling RLS
-- with zero policies is a deny-all that keeps roll numbers, medical reasons and
-- proof metadata unreachable through the Data API even if the anon key leaks.

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE permission_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE proof_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_records ENABLE ROW LEVEL SECURITY;

-- Staff accounts. microsoft_id is filled in automatically on first Entra sign-in,
-- so the placeholder below only reserves the email -> role mapping.
INSERT INTO users (microsoft_id, email, name, role, department) VALUES
('hod-microsoft-id', 'hod.cse@adityauniversity.in', 'Dr. S. Raghavan', 'HOD', 'CSE'),
('lecturer1-microsoft-id', 'lecturer1.cse@adityauniversity.in', 'Dr. Anil Kumar', 'LECTURER', 'CSE'),
('lecturer2-microsoft-id', 'lecturer2.cse@adityauniversity.in', 'Prof. Meera Sharma', 'LECTURER', 'CSE')
ON CONFLICT (email) DO NOTHING;

-- Students. The roll number doubles as the university mailbox prefix and as
-- the Outlook display name, which is why name mirrors it.
INSERT INTO users (microsoft_id, email, name, roll_number, phone, role, department) VALUES
('student1-microsoft-id', '26b21cs058@adityauniversity.in', '26B21CS058', '26B21CS058', '9876543210', 'STUDENT', 'CSE'),
('student2-microsoft-id', '26b21cs059@adityauniversity.in', '26B21CS059', '26B21CS059', '9876543211', 'STUDENT', 'CSE'),
('student3-microsoft-id', '25b21cs012@adityauniversity.in', '25B21CS012', '25B21CS012', '9876543212', 'STUDENT', 'CSE'),
('student4-microsoft-id', '24b21cs145@adityauniversity.in', '24B21CS145', '24B21CS145', '9876543213', 'STUDENT', 'CSE')
ON CONFLICT (email) DO NOTHING;

COMMIT;
